name: Purge CDN Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jsDelivr Purge
        run: |
          curl -I "https://purge.jsdelivr.net/gh/lotsacookie/kstuff@main/script.js"
          curl -I "https://purge.jsdelivr.net/gh/lotsacookie/kstuff@main/style.css"
          curl -I "https://purge.jsdelivr.net/gh/lotsacookie/kstuff@main/Json/g.json"
          curl -I "https://purge.jsdelivr.net/gh/lotsacookie/kstuff@main/Json/a.json"
          curl -I "https://purge.jsdelivr.net/gh/lotsacookie/kstuff@main/Json/categories.json"
