name: Purge CDN Cache

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  purge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger jsDelivr Purge
        run: |
          curl -I "https://purge.jsdelivr.net/gh/lotsacookie/kstuff@main/"
